name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  ecr-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: test-aws-deploy
        region: us-east-2
        tags: latest,${{ github.sha }}
