# name: Deploy to AWS

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 1
#       - name: Install Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '>=13.2'
      # - name: Install build dependencies
      #   run: yarn install --production
      # - name: Build static files
      #   run: yarn build
      #   env:
      #     GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
      #     GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
      # - name: Install Google Cloud
      #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     version: '274.0.1'
      #     service_account_key: ${{ secrets.GCLOUD_AUTH }}
      # - name: Deploy files
      #   run: yarn run --verbose ssdeploy deploy
      #   env:
      #     GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
      #     GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      #     CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      #     CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
